import type { MetadataRoute } from "next";

/**
 * Weaver PWA manifest (§8 PWA-first). Generated via Next.js App Router so it's
 * typed and auto-linked into <head>. Icons live in /public (add real ones later).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Weaver — your visual taste, woven together",
    short_name: "Weaver",
    description:
      "A personal aggregator that gathers images you've engaged with across your accounts and ranks them to your taste.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    orientation: "portrait-primary",
    // Orb-weaver web icons, generated by scripts/gen-icons.mjs (brand motif).
    // "any" for the launcher, "maskable" (art in the safe zone) for adaptive
    // icons that get circle/squircle-cropped. iOS uses src/app/apple-icon.png.
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
