import type { MetadataRoute } from "next";

/**
 * Weaver PWA manifest (§8 PWA-first). Generated via Next.js App Router so it's
 * typed and auto-linked into <head>. Icons live in /public (add real ones later).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Weaver — your visual taste, woven together",
    short_name: "Weaver",
    description:
      "A personal aggregator that gathers images you've engaged with across your accounts and ranks them to your taste.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    orientation: "portrait-primary",
    // Orb-weaver web icons, generated by scripts/gen-icons.mjs (brand motif).
    // "any" for the launcher, "maskable" (art in the safe zone) for adaptive
    // icons that get circle/squircle-cropped. iOS uses src/app/apple-icon.png.
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // Web Share Target: once installed, Weaver appears in the OS "Share" sheet.
    // Sharing an image FILE or a LINK from any app (Instagram, Pinterest, a
    // browser…) posts here — /api/share resolves it to an image, embeds it, and
    // adds it to the taste set. No platform API, no scraping, uses the user's own
    // session. The typed manifest doesn't cover share_target yet, so cast it.
    ...( {
      share_target: {
        action: "/api/share",
        method: "POST",
        enctype: "multipart/form-data",
        params: {
          title: "title",
          text: "text",
          url: "url",
          files: [{ name: "image", accept: ["image/*"] }],
        },
      },
    } as object),
  };
}
